### ISSUE TITLE
getkeys.php returns fatal error

### ISSUE THREAD

**Issue by ivtvi** [aejr/secter#1]
NETWORK: getKeysReply: sending: "<?xml version="1.0"?><request><type>get_keys</type><session_key>b26f29c24644cb0d25f9338b39316078</session_key><number>2</number><friend>xelexin1</friend><friend>asd2</friend></request>"
NETWORK: getKeysReply: recived: "<br /> <b>Fatal error</b>: Call to a member function bind_param() on a non-object in <b>/home/users/bobas/public_html/rafal/tin/getkeys.php</b> on line <b>46</b><br />"

**Comment by xelexin** [comment]
teraz działa?

**Comment by ivtvi** [comment]
ok działa
