### ISSUE TITLE
jaki padding do Janka

### ISSUE THREAD

**Issue by edek7** [aejr/secter#10]
siema Janek zastanawiam się jak rozkodować wiadomość . i jaki padding użyć w Cipher 
Wrzucam link 
mam nadzieje ze sie kapniesz o co chodzi 

http://docs.oracle.com/javase/7/docs/api/javax/crypto/Cipher.html

**Comment by ivtvi** [comment]
obecnie jest EME_PKCS1_OAEP 	- Optimal asymmetric encryption padding (PKCS#1, Version 2.0) 
ale można go zmienic

**Comment by edek7** [comment]
dobra juz zrobiłem ::P 
dzięki
