### ISSUE TITLE
Wiele kluczy

### ISSUE THREAD

**Issue by mostua** [aejr/secter#4]
Pobieranie wiadomośći gdy ma sie wiele kluczy jest zbugowane, nawet jeśli wszystkie klucze są poprawne.

**Comment by xelexin** [comment]
co to znaczy zbugowane?

**Comment by mostua** [comment]
To znaczy ze jak mam wiele kluczy w systemie (ważnych) to albo nasz kontroler nawala albo Twoj skrypt i nic nie dostaje.

**Comment by mostua** [comment]
Z tego co widze Janek naprawil, zamykam
